feature/30/any messgae

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,23 +1,20 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-message="$(cat $1)"
-requiredPattern="^feature/[0-9]+/.*$"
-if ! [[ $message =~ $requiredPattern ]];
-then
-  echo "-"
-  echo "-"
-  echo "-"
-  echo "🚨 Wrong commit message! 😕"
-  echo "The commit message must have this format:"
-  echo "<verb in imperative mood> <what was done>"
-  echo "Allowed verbs in imperative mood: add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge"
-  echo "Example: add login button"
-  echo "-"
-  echo "Your commit message was:"
-  echo $message
-  echo "-"
-  echo "For more information, check script in .husky/commit-msg"
-  echo "-"
+message=$(cat "$1")
+requiredPattern="^feature/[0-9]+/.+$"
+if ! echo "$message" | grep -iqE "$requiredPattern"; then
+  echo >&2 "-"
+  echo >&2 "-"
+  echo >&2 "-"
+  echo >&2 "🚨 Wrong commit message! 😕"
+  echo >&2 "The commit message must have this format:"
+  echo >&2 "feature/<any number>/<any message>"
+  echo >&2 "-"
+  echo >&2 "Your commit message was:"
+  echo >&2 "$message"
+  echo >&2 "-"
+  echo >&2 "For more information, check script in .husky/commit-msg"
+  echo >&2 "-"
   exit 1
 fi
